// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WASHDAY_202508.Data;

#nullable disable

namespace WASHDAY_202508.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250826033821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("WASHDAY_202508.Data.DailyLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Expenses")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Others")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SalesWalkIn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Sunvida")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("DailyLedgers");
                });
#pragma warning restore 612, 618
        }
    }
}
