// <auto-generated />
using System;
using CebuCrmApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CebuCrmApi.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260415052010_AddLeadCebuFields")]
    partial class AddLeadCebuFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CebuCrmApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyingTimeline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interest")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestmentPurpose")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForeigner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOfw")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextFollowUp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentAbility")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferences")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = "4M - 6M PHP",
                            BuyingTimeline = "Within 3 Months",
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@example.com",
                            Interest = "Condo",
                            InvestmentPurpose = "Rental Income",
                            IsForeigner = false,
                            IsOfw = true,
                            Name = "Maria Santos",
                            Nationality = "Filipino",
                            NextFollowUp = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Looking for an investment-friendly Cebu unit for family use and Airbnb.",
                            PaymentAbility = "Bank Financing",
                            Phone = "09171234567",
                            Preferences = "2BR condo near the airport with short-term rental upside",
                            PreferredArea = "Mactan / Airport Area",
                            Source = "Facebook",
                            Status = "Contacted"
                        },
                        new
                        {
                            Id = 2,
                            Budget = "6M - 8M PHP",
                            BuyingTimeline = "Immediate",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Interest = "House & Lot",
                            InvestmentPurpose = "Rental",
                            IsForeigner = true,
                            IsOfw = false,
                            Name = "John Smith",
                            Nationality = "American",
                            NextFollowUp = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Needs clear foreign-buyer guidance and ROI estimate.",
                            PaymentAbility = "Cash",
                            Phone = "09189876543",
                            Preferences = "RFO condo in IT Park with long-term rental potential",
                            PreferredArea = "IT Park / Cebu City",
                            Source = "Referral",
                            Status = "Site Visit"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentPlan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("UnitId");

                    b.ToTable("Deals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeadId = 1,
                            Notes = "Lead wants a flexible payment plan and Airbnb-ready turnover.",
                            PaymentPlan = "30% DP over 24 months, 70% bank financing",
                            PriceSnapshot = 6350000m,
                            Stage = "Reservation",
                            UnitId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeadId = 2,
                            Notes = "Schedule a second viewing with spouse on Saturday.",
                            PaymentPlan = "20% DP then cash-out on turnover",
                            PriceSnapshot = 7200000m,
                            Stage = "Site Visit",
                            UnitId = 3
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.DealActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealId = 1,
                            Note = "Discussed payment terms and rental strategy.",
                            Type = "Call"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealId = 1,
                            Note = "Sent reservation confirmation and next payment reminder.",
                            Type = "Follow-up"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealId = 2,
                            Note = "Walked through amenity deck and model unit.",
                            Type = "Site Visit"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.DealPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("DealPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 50000m,
                            Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealId = 1,
                            Note = "Reservation fee received",
                            Type = "Reservation"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 180000m,
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DealId = 1,
                            Note = "First down payment installment",
                            Type = "DP"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.InvestmentSnapshot", b =>
                {
                    b.Property<int>("DealId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AirbnbEstimate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("RentalEstimate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Roi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DealId");

                    b.ToTable("InvestmentSnapshots");

                    b.HasData(
                        new
                        {
                            DealId = 1,
                            AirbnbEstimate = 51000m,
                            RentalEstimate = 32000m,
                            Roi = 8.4m,
                            UpdatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DealId = 2,
                            AirbnbEstimate = 56000m,
                            RentalEstimate = 35000m,
                            Roi = 7.1m,
                            UpdatedAt = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "AboitizLand",
                            Location = "Mactan, Cebu",
                            Name = "Mactan Seaview Residences",
                            Type = "Pre-selling"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Ayala Land",
                            Location = "IT Park, Cebu City",
                            Name = "IT Park Central",
                            Type = "RFO"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bedrooms = 2,
                            Location = "Mactan, Cebu",
                            Price = 4500000m,
                            Status = "Available",
                            Title = "Mactan Ocean View Condo",
                            Type = "Pre-selling"
                        },
                        new
                        {
                            Id = 2,
                            Bedrooms = 1,
                            Location = "IT Park, Cebu City",
                            Price = 3200000m,
                            Status = "Negotiating",
                            Title = "IT Park Studio Unit",
                            Type = "Resale"
                        },
                        new
                        {
                            Id = 3,
                            Bedrooms = 4,
                            Location = "Busay",
                            Price = 12000000m,
                            Status = "Sold",
                            Title = "Busay Mountain Villa",
                            Type = "Resale"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CebuCrmApi.Models.ServiceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            ClientName = "Maria Santos",
                            Notes = "Express wash",
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceType = "Laundry",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500m,
                            ClientName = "",
                            Notes = "Unit 1202, IT Park",
                            OrderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceType = "Airbnb Cleaning",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FloorPlanUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SizeSqm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorPlanUrl = "https://example.com/floorplans/sv-1208",
                            Price = 4850000m,
                            ProjectId = 1,
                            SizeSqm = 38.5m,
                            Status = "Available",
                            UnitCode = "SV-1208"
                        },
                        new
                        {
                            Id = 2,
                            FloorPlanUrl = "https://example.com/floorplans/sv-1512",
                            Price = 6350000m,
                            ProjectId = 1,
                            SizeSqm = 52.0m,
                            Status = "Reserved",
                            UnitCode = "SV-1512"
                        },
                        new
                        {
                            Id = 3,
                            FloorPlanUrl = "https://example.com/floorplans/it-0810",
                            Price = 7200000m,
                            ProjectId = 2,
                            SizeSqm = 44.0m,
                            Status = "Available",
                            UnitCode = "IT-0810"
                        },
                        new
                        {
                            Id = 4,
                            FloorPlanUrl = "https://example.com/floorplans/it-1015",
                            Price = 7900000m,
                            ProjectId = 2,
                            SizeSqm = 48.0m,
                            Status = "Sold",
                            UnitCode = "IT-1015"
                        });
                });

            modelBuilder.Entity("CebuCrmApi.Models.Booking", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Deal", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Client", "Lead")
                        .WithMany("Deals")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CebuCrmApi.Models.Unit", "Unit")
                        .WithMany("Deals")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CebuCrmApi.Models.DealActivity", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Deal", "Deal")
                        .WithMany("Activities")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("CebuCrmApi.Models.DealPayment", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Deal", "Deal")
                        .WithMany("Payments")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("CebuCrmApi.Models.InvestmentSnapshot", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Deal", "Deal")
                        .WithOne("InvestmentSnapshot")
                        .HasForeignKey("CebuCrmApi.Models.InvestmentSnapshot", "DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Unit", b =>
                {
                    b.HasOne("CebuCrmApi.Models.Project", "Project")
                        .WithMany("Units")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Client", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Deal", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("InvestmentSnapshot");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Project", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("CebuCrmApi.Models.Unit", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
